# Generated by Django 3.2.5 on 2021-07-11 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_title', models.CharField(default='', max_length=60)),
                ('own_text', models.TextField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(default='', max_length=50)),
                ('tagstotopics', models.ManyToManyField(to='weblog.Entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='own_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.topic'),
        ),
    ]
